service: promodb

custom:
  defaultStage: test

provider:
  name: aws
  stage: ${opt:stage}
  description: promoapp db
  runtime: nodejs14.x
  region: eu-west-1

resources:
  Resources:
    citiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventimages${file(../env-${self:provider.stage}.json):DB_PREFIX}
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: delete_in
          Enabled: true