const stringMessages = {
    PROMO_TEAM: "Promo team",
    DATA: "data",
    ADMIN_LOGIN_TYPE: "admin",
    USD: "USD",
    USER: "User",
    EVENT: "event",
    YOUR: "Your",
    REWARD: "Reward"
}

const successMessages = {
    SUCCESS_LOGIN: "Success, you are successfully login",
    ACCOUNT_VERIFIED_SUCCESSFULLY: "Success, account verified successfully!",
    ENTER_OTP_TO_VERIFY_EMAIL: "Enter six digit One Time Passoword we sent to your email to verify",
    VERIFY_MOBILE_OTP_SENT: "Enter six digit One Time Passoword we sent to your mobile number to verify",
    OTP_IS_EXPIRED_VERIFY_OTP_SENT: "Look like your One Time Passoword is expired, please enter six digit One Time Passoword we sent to your mobile number to verify",
    SOCIAL_SHARE_INFO_SAVED: "Social share information saved successfully!",
    GET_USER_EVENT_LIST: "User event list successfully!",
    GET_EVENT_LIST: "Event list successfully!",
    GET_UPCOMING_EVENT_LIST: "Up Coming Event Record",
    GET_PAST_EVENT_LIST: "Past Event",
    REFUNDED_AND_CANCELLED_TICKETS: "Refunded And Cancelled Tickets",
    GET_ALL_TICKETS: "All Tickets",
    GET_EVENT_ANALYTICS: "Get Event Analytics successfully!",
    GET_REPORT: "Get Report successfully!",
    GET_ORGANISER_REPORT: "Organiser report!",
    GET_EVENT_TICKETS: "Get event tickets Data successfully!",
    GET_REWARD_ANALYTICS: "Reward analytics!",
    GET_USER_SHARED_EVENTS: "User shared events list",
    REGISTERED: "Register Successful!",
    OTP_VERIFIED: "One Time Passoword verified successfully!",
    LOGOUT_AND_TOKEN_DELETED: "Logout and Token deleted Successfully",
    PASSWORD_CHANGED: "Password changed Successfully",
    PASSWORD_UPDATED: "Success, user password updated successfully",
    VISITED_INFO_SAVED: "Visited information saved successfully!",
    VERIFY_EMAIL_LINK_SENT_TO_MAIL: "Success, verify email link sent to email, please check your mail!",
    EMAIL_VERIFIED: "Success, your email verified successfully!",
    OTP_VERIFIED_MOBILE_NO_UPDATED: "One time password verified successfully, mobile number updated!",
    CARD_ADDED: "Card added successfully!",
    ACCPUNT_VERIFIED: "Your account has been verified!",
    ACCOUNT_STATUS_IS_UNDER_REVIEW: "Your account status is under review!",
    ACCOUNT_APPROVED: "Your account is approved",
    CARD_REMOVED: "Card removed successfully!",
    GET_USER_CARD: "User card details",
    VALID_COUPON_CODE: "Coupon code is valid",
    GET_GATEWAY_ID: "Gateway Id",
    GET_MY_PLAN: "My Plan.",
    EVENT_HIGHLIGHT_PAYMENT_PAID: "Event highlight payment successfully paid.",
    USER_PLAN_UNSUBSCRIBED: "User plan unsubscribed successfully",
    CARD_UPDATED: "Card updated successfully!",
    USER_CARD_CHANGED: "User defult card changed",
    COMMENT_ADDED: "Comment added successfully!",
    COMMENT_DELETED: "Comment deleted successfully!",
    EVENT_CREATED: "Event create successfully!",
    VISITED: "Visited successfully!",
    TICKET_ADDED: "Ticket added successfully",
    TICKET_ALREADY_PURCHASED_BY_OTHER: "This event tickets already purchased by other. You can not change payout bank now.",
    PAYOUT_BANK_CHANGED: "Payout bank changed successfully.",
    EVENT_CLAIMED: "Event claimed successfully",
    GUEST_DELETED: "Guest deleted successfully!",
    TICKET_DELETED: "Ticket deleted successfully",
    USER_SOCIAL_DYNAMIC_LINK_FOUND: "User social dynamic link found!",
    AMOUNT_REFUNDED: "Amount refunded successfully",
    ALL_TICKET_PROCESS_COMPLETED: "all ticket process was completed successfull",
    EVENT_CANCELLED: "Your event was cancelled successfully!",
    VALID_EVENT_CANCEL_REQUEST: "valid event cancel request!",
    REPUBLISH_EVENT_CREATED: "Republish Event created successfully",
    USER_SHARED_EVENT: "User shared this event successfully!",
    ADDRESS_UPDATED: "Address updated Successfully.",
    EVENT_UPDATED: "Event updated successfully!",
    EVENT_IMAGE_UPDATED: "Event image updated successfully.",
    USER_RESPONSE_SAVED: "User response save Successfully.",
    GET_USER_MONTHLY_EVENT_DETAILS: "Monthly user event details",
    GET_COMMENT_LIST: "Comment list successfully!",
    EVENT_DELETED: "Event delete successfully!",
    MESSAGE_SENT: "Your message has been successfully sent. We are get back to you soon.",
    GET_USER_LIST: "All User List",
    GET_BUG_TYPE: "Bug report type listing",
    GET_CATEGORY_LIST: "All Category List",
    GET_NOTIFICATION: "Notification",
    FEEDBACK_SENT: "FeedBack sent.",
    NOTIFICATION_PUSHED: "Notification pushed successfully.",
    BUG_REPORTED: "Bug report submitted",
    GET_FOLLOWINGS_LIST: "Followings List",
    GET_FOLLOWERS_LIST: "Followers List",
    GET_FOLLOW_LIST: "Get Followings And Followers List Successfully!",
    USER_ACTIVE_PAYOUT_EVENTS: "User payout events",
    USER_HAVE_NO_ACTIVE_PAYOUT_EVENTS: "User have not any payout event",
    USER_COMPLETED_PAYOUT_EVENTS: "User completed payout events",
    USER_PENDING_PAYOUT_EVENTS: "User pending payout events",
    GET_PROFILE: "Profile data",
    GET_GOING_EVENTS: "Going Events",
    GET_INTERESTED_EVENTS: "Interested Events",
    PAYPAL_EMAIL_UPDATED: "Paypal email updated Successfully.",
    PROFILE_UPDATED: "Profile updated Successfully.",
    REWARD_CREATED: "Reward create successfully!",
    WINNER_INFO_SAVED: "Winner information saved successfully!",
    REWARD_DELETED: "Reward delete successfully!",
    GET_REWARD_LIST: "Reward list successfully!",
    REWARD_UPDATED: "Reward update successfully!",
    SEATING_PLAN_SAVED: "Seating plan details saved successfully!",
    SEATING_PLAN_REMOVED: "Seating plan removed successfully!",
    USER_HOLD_TICKET_DELETED: "Success, User's hold seat removed successfully!",
    GET_EXISTING_SEATING_PLAN: "Success, existing seating plan details found!",
    GET_SEATING_PLAN: "Success, seating plan details found!",
    GET_SEATING_PLAN_TICKET: "Success, seating plan ticket details found!",
    GET_USER_HOLD_TICKET: "Success, user hold seats get successfully!",
    SEAT_HOLD: "Success, seat hold successfully!",
    HOLD_SEAT_REMOVED: "Success, hold seat removed successfully!",
    SEATING_PLAN_UPDATED: "Seating plan details updated successfully!",
    SUCCESS: "success!",
    ACTIVE_EVENTS_NOT_FOUND: "active events not found!",
    GET_INSIDE_EVENT: "Inside event Details",
    GET_TICKET_PURCHASED: "TIcket purchased details",
    TICKETS_PURCHASED: "User tickets purchased successfully",
    TICKET_UPDATED: "Event Ticket detail updated successfully!",
    TICKET_CANCELLED: "Your ticket has been cancelled successfully!",
    ORGANISER_TICKET_CANCELLED: "Ticket was cancelled successfully!",
    USER_TICKET_CANCELLED: "Your ticket was cancelled successfully!",
    USER_CHECKED_IN: "User checked-in successfully",
    GET_TICKET_DETAILS: "Ticket details.",
    PAYMENT_INTENT: "payment intent details",
    TOKEN_STORED: "Token stored Successfully",
    GET_FOLLOW_STATUS: "Follow status",
    STRIPE_ACCOUNT_ADDED: "Stripe Account added successfully.",
    EVENT_ADMINISTATOR_CREATED: "Success, You are successfully become a administrator of the event, please login to manage the event!",
    GET_EVENT_ADMINISTATOR_INVITATION_HISTORY: "Success, Event administrator invitation history found.",
    USER_FOLLOWED: "User Followed Successfully",
    GET_USER_GROUP: "User guest users group details found!",
    INVITATION_SENT: "Success, Invitation send successfully!",
    USERS_NOT_EXISTS: "users not exist on our system",
    BANK_ACCOUNT_LINKED: "Bank account linked with user account",
    GET_BANK_ACCOUNT_LIST: "Bank accounts listings",
    BANK_ACCOUNT_CHANGED: "Default bank account changed successfully",
    STRIPE_ACCOUNT_CREATED: "Stripe account link",
    USER_UNFOLLOWED: "User unfollowed.",
    BANK_DETAILS_UPDATED: "bank details updated",
    GET_BANK_ACCOUNT_DETAILS: "Bank account details",
    BANK_ACCOUNT_REMOVED: "bank account removed successfully",
    GET_USER_GOING_IN_EVENT_STATUS: "User event going status",
    EVENT_ADMINISTATOR_APPROVAL_INVITATION_PROCEEDED: "Success, Your request for approval invitation of an event administrator has successfully proceeded, please sign up on the promoapp to become a event administrator!",
    EVENT_ADMINISTATOR_REJECT_INVITATION_PROCEEDED: "Success, Your request to reject invitation of an event administrator has successfully proceeded!",
    SEND_VERIFICATION_CODE_TO_MAIL: "We'll send an account verification code to your email",
    VERIFY_ACCOUNT_FIRST: "Please verify your account first for further processing.",
    GET_ZONE_EVENTS_LIST: "Events list data",
    VERIFIED: " verified!",
    OTP_VERIFIED: "One time password verified!",
    MOBILE_ALREADY_VERIFIED: "Suceess, mobile number already verified!",
    EMAIL_ADDED: "Email added successfully",
    EMAIL_SENT: "Email Sent Successfully",
    LOCATION_ADDED: "Location added successfully",
    USER_QUALIFY: "User qualify",
    USER_DISQUALIFY: "User disqualify",
    GET_ZONE_DETAILS: "Zone details found.",
    GET_ZONE_LIST: "Zone list data",
    GET_USER_MEMBER_ZONE_LIST: "user member zone list",
    GET_USER_ZONE_LIST: "Users zone listing data",
    LEFT_ZONE: "Success, You have successfully left this zone.",
    GET_ZONE_MEMBER_LIST: "Zone Members list data",
    GET_ZONE_OWNER_LIST: "Zone Owners list data",
    GET_ZONE_ORGANIZERS_LIST: "Zone Organizers listing data",
    ZONE_MEMBER_BLOCKED: "Zone member blocked successfully.",
    ZONE_ORGANIZER_BLOCKED: "Zone organizer blocked successfully.",
    ZONE_ORGANIZER_UNBLOCKED: "Zone organizer unblocked successfully.",
    ZONE_MEMBER_UNBLOCKED: "Zone member unblocked successfully.",
    GET_ZONE_MEMBER: "Zone member details found.",
    ZONE_MEMBER_REMOVED: "Success, zone member removed successfully.",
    ZONE_EVENT_DELETED: "Success, event removed successfully from the zone.",
    ZONE_ORGANIZER_DELETED: "Success, zone organizer removed successfully.",
    ZONE_OWNER_REMOVED: "Success, zone owner removed successfully.",
    ZONE_OWNER_DASHBOARD: "Zone Owner Dashboard Detail",
    INVITATION_REJECTED: "Success, Invitation rejected successfully",
    ZONE_MEMBER_DETAIL_UPDATED: "Success, zone member details updated successfully.",
    INVITATION_REQUEST_SAVED: "Success, Invitation request saved successfully!",
    EVENT_ALREADY_HAVE_IMAGE: "Event already have the image",
    BECOME_MEMBER_OF_ZONE: "Success, You're successfully become a member of the",
    BECOME_ORGANIZER_OF_ZONE: "Success, You are successfully become an organizer in the",
    BECOME_OWNER_OF_ZONE: "Success, You are successfully become a owner of the",
    JOIN_ZONE_REQUEST_REGISTERED1: "Success, Your request for joining the",
    JOIN_ZONE_REQUEST_REGISTERED2: "zone is registred successfully. We will send next mail for the approval or rejection shortly.",
    GET_ATTENDEE_DETAILS: "Get Attendee list successfully!",
    DISCOUNT_CODE_ADDED: "Discount code added successfully!",
    DISCOUNT_CODE_UPDATED: "Discount code updated successfully!",
    DISCOUNT_CODE_VALID: "Discount code is valid",
    DISCOUNT_CODE_GET_DATA: "Discount codes data get succesfully!",
    DISCOUNT_CODE_DELETED: "Discount code deleted succesfully!"
}

const smsMessages = {
    OTP_FOR_SIGNIN: " is your One Time Passoword for signin into promo app. One Time Passoword are secret, do not share with anyone",
    OTP_FOR_SIGNUP: " is your One Time Passoword for registering with promo app. One Time Passoword are secret, do not share with anyone",
}

const errorMessages = {
    SERVER_ERROR_TRY_AGAIN: "Server error! Please try again later",
    INVALID_MOBILE: "Please enter a valid mobile number",
    INVALID_EMAIL: "Please enter a valid email address",
    INVALID_PASSWORD: "Please enter a correct password",
    REQUIRE_COUNTRY_CODE: "Please enter country code",
    EMAIL_REQUIRED: "Email is required",
    REQUIRE_MOBILE_NUMBER: "Please provide mobile number",
    REQUIRE_MOBILE_NUMBER_OR_EMAIL: "Failure, invalid request params, provide either mobile number or email to login!",
    BOTH_NOT_ALLOWED_MOBILE_NUMBER_AND_EMAIL: "Failure, both mobile number and email not allowed together, either provide mobile number or email to login!",
    PASSWORD_IS_TOO_OLD_PLEASE_RESET_PASSWORD: "Your password is too old, please reset your password. We have sent link to your registered email address.",
    USER_NOT_EXISTS_WITH_GIVEN_MOBILE_AND_COUNTRY_CODE: "Failure, User not exists with given mobile number and country code!",
    INVALID_SIGNIN_TYPE: "Failure, invalid signin type, please provide valid signin type!",
    INVALID_SIGNUP_TYPE: "Failure, invalid signup type, please provide valid signup type!",
    ORGANISER_DEVICE_ID_NOT_FOUND: "Organiser device id not found",
    SOCIAL_SHARE_INFO_ALREADY_SAVED: "Social share information already saved!",
    NO_EVENTS_FOUND: "No events found!",
    NO_RECORD_FOUND: "No record found!",
    NO_TICKETS_BOOKED: "No tickets booked.",
    ATTENDEE_NOT_FOUND: "Attendee details not found!",
    EVENT_NOT_FOUND: "Event not found!",
    ORGANISER_NOT_FOUND: "Organiser details not found!",
    EVENT_ORGANISER_NOT_FOUND: "Event organiser details not found!",
    INVALID_EVENT_ORGANISER_ID: "Getting invalid event organiser id while canceling ticket!",
    REFRENCE_USER_NOT_FOUND: "Refrence user details not found!",
    USER_IS_NOT_MEMBER_ZONE_LIST: "user is not member in any zone",
    OTP_EXPIRED: "One Time Passoword expired, try again later!",
    USER_NOT_FOUND_WITH_GIVEN_EMAIL: "Failure, user details not found with given email!",
    USER_DEVICE_ID_NOT_FOUND: "User device id not found",
    INVALID_REPORT_TYPE: "Invalid Report Type",
    NO_SHARED_EVENT: "No shared event",
    VALIDATION_ERROR: "Validation Error! Please check values",
    AUTHORIZATION_ERROR: "Authorization error. Not allowed",
    USER_ALREADY_EXISTS: "User already exists! Please login instead",
    INCORRECT_USER_OR_OTP: "No such user or incorrect One Time Password",
    EMAIL_ALREADY_EXIST: "Email already exist",
    INCORRECT_PASSWORD_TOKEN: "Incorrect Password Token!",
    INCORRECT_PASSWORD: "Incorrect Password!, Please enter valid password.",
    EMAIL_NOT_INVITED_TO_THIS_EVENT: "This email is not invited to this event. Please login or signup with the email you recieved this event invite on",
    INVITE_LINK_INVALID_OR_EXPIRED: "This invite link is invalid or expired. Please check you email for a new link or contact administrator",
    LOGIN_TO_VIEW_EVENT: "Please login to view this event",
    PASSWORD_REQUIRED_TO_VIEW_EVENT: "Please provide password to view this event",
    INVALID_INPUT: "Invalid input",
    INVALID_TICKETID: "Invalid TicketId",
    NO_COMMENT_FOUND: "No comment found!",
    TOKEN_DOES_NOT_EXIST: "Token does not exist.",
    INCORRECT_USER_OR_UNAUTHORIZED: "User not found or unauthorized user",
    INVALID_USER: "Invalid User",
    EMAIL_NOT_EXIST: "Email not exists in system",
    NO_SUCH_KEY_OR_ALREADY_USED: "Login key invalid or alredy used",
    REQUIRE_MOBILE_NUMBER_AND_COUNTRY_CODE: "Required to fill mobile number and country code to register!",
    ALREADY_REGISTERED_MOBILE_NUMBER_AND_COUNTRY_CODE: "Failure, mobile number and country code already registered, try another one!",
    CARD_DETAILS_NOT_FOUND: "Card details not found",
    USERNAME_ALREADY_REGISTERED_WITH_QUICKBLOX: "Failure, username already registered with quickblox!",
    USERNAME_AND_EMAIL_REQUIRED: "Required to fill username and email to register",
    EMAIL_NOT_EXIST_IN_YOUR_ACCOUNT: "Failure, email not exists in your account!",
    USER_NOT_FOUND: "Failure, user details not found!",
    INVALID_OTP: "Failure, Invalid one time password or doesn't match!",
    INVALID_COUPON_CODE: "Coupon code is not valid",
    COUPON_CODE_NOT_FOUND: "Coupon code not found",
    EVENT_ALREADY_STARTED: "Event already been started",
    NOT_SUBSCRIBED_TO_THIS_PLAN: "You are not subscribed to this plan",
    NOT_SUBSCRIBED_ANY_PLAN: "You are not subscribed any plan",
    TICKET_NOT_FOUND: "Ticket not found",
    UNABLE_TO_ADD_EMAIL: "Unable to add email",
    DATA_NOT_FOUND: "No Data found",
    NO_LAT_LONG_RECEIVED: "No lat and long received",
    REWARD_NOT_FOUND: "Reward details not found!",
    IMAGE_NOT_UPDATED: "Image not updated.",
    INVALID_TOKEN: "Invalid token!",
    YOU_CAN_NOT_CANCEL_THIS_EVENT: "You can not cancel this event!",
    YOU_CAN_NOT_EDIT_THIS_EVENT: "You can not edit this event",
    USER_ALREADY_SHARED_EVENT: "User already shared this event",
    USER_CAN_NOT_DELETE_THIS_EVENT: "User can not delete this ticket.",
    EVENT_TICKET_NOT_BELONGS_TO_THIS_USER: "This ticket event not belongs to this user.",
    YOU_ARE_NOT_ABLE_TO_CLAIM_THIS_EVENT: "You are not able to claim this event",
    USER_HAVE_NOT_ANY_TRANSACTION_HISTORY: "This user have not any transaction history",
    USER_NOT_BELONG_WITH_THIS_BANK_ACCOUNT: "User not belog with this bank account.",
    USERNAME_ALREADY_HAS_BEEN_USED: "Username already has been used",
    USER_HAVE_NOT_CREATED_THIS_REWARD: "This user have not created this reward",
    EMAIL_ALREADY_HAS_BEEN_USED: "Email address already has been used",
    REWARD_ALREADY_CREATED_FOR_THIS_EVENT: "Reward already created for this event!",
    INVALID_TICKET: "This ticket is not valid",
    SEATING_PLAN_NOT_FOUND: "Failure, seating plan not found!",
    SOMETHING_WRONG_WHILE_SAVING_SEATING_DATA: "Failure, something wrong while saving seating data!",
    EVENT_STATUS_IS_COMPLETE: "event_status is with complete status",
    ONLY_EVENT_ORGANIZER_HAS_ACCESS_TO_DELETE_EVENT: "Failure, The only event organizer has access to delete an event!",
    SOMETHING_WENT_WRONG: "Failure, Something went wrong, please try again later!",
    VISITED_INFO_ALREADY_SAVED: "Visited information already inserted!",
    WINNDER_INFO_ALREADY_SAVE: "Winner information already saved!",
    REWARD_IS_NOT_BELONG_TO_THIS_USER: "This reward is not belogs to this user.",
    LAYOUT_ALREADY_CREATED_FOR_THIS_EVENT: "Failure, layout already created for this event!",
    EXISTING_SEATING_PLAN_NOT_FOUND: "Failure, existing seating plan details not found!",
    SOMETHING_WRONG_WHILE_GETTING_EXISTING_SEATING_PLAN: "Failure, something wrong while getting existing site plan!",
    SOMETHING_WRONG_WHILE_GETTING_SEATING_PLAN: "Failure, something wrong while getting seating plan!",
    SOMETHING_WRONG_WHILE_GETTING_SEATING_PLAN_TICKET_DETAILS: "Failure, something wrong while getting seating plan ticket details!",
    INSUFFICIENT_TICKETS: "Have not sufficient Tickets",
    SOME_SELECTED_SEATS_ALREADY_BOOKED: "Failure, some of selected seats already booked!",
    SOMETHING_WRONG_WHILE_UPDATING_SEATING_PLAN: "Failure, something wrong while updating seating plan details!",
    QR_DOES_NOT_BELONG_TO_THIS_EVENT: "This QR code does not belong to this event",
    USER_ALREADY_CHECKED_IN_ON_THIS_EVENT: "User already checked-in on this event",
    ALREADY_CHECKED_IN_TICKET: "Already Checked-In at <checkedinAt>",
    INVITATION_EXPIRED: "Failure, Invitaion expired, try again later when get a new invitation!",
    USER_NOT_FOUND_WITH_GIVEN_MAIL_COMPLETE_REGISTRATION_TO_BECOME_EVENT_ADMINISTRATOR: "Failure, User not found in a system with given email, please complete the registration process to become event administrator!",
    USER_ALREADY_FOLLOWED: "User already followed.",
    USER_HAVE_NOT_LINKED_ACCOUNT: "User have not linked any account",
    REQUIRED_BANK_TOKEN_TO_UPDATE: "Please provide bank token to update details.",
    REQUIRED_BANK_TOKEN_TO_DELETE: "Please provide bank token to delete account.",
    ALREADY_REJECTED_EVENT_ADMINISTRATOR_INVITATION: "Failure, You are alredy rejected invitation of the event administrator for this event!",
    ALREADY_REJECTED_EVENT_ADMINISTRATOR_INVITATION_TRY_AGAIN_WHEN_GET_NEW_INVITATION: "Failure, You are alredy rejected invitation of the event administrator for this event, please try again when you get a new invitation to be event administrator!",
    ALREADY_EVENT_ADMINISTRATOR_SO_CAN_NOT_REJECT_INVITATION: "Failure, You are already the administrator of the event, you can not able to reject invitation now!",
    ALREADY_EVENT_ADMINISTRATOR_LOGIN_TO_MANAGE_EVENT: "Failure, You are already administrator of the event, please login to manage the event!",
    ZONE_NOT_FOUND: "Zone details not found.",
    ZONE_MEMBER_NOT_FOUND: "Zone member details not found.",
    INVALID_ZONE_ID: "Failure, Invalid zone id.",
    INVALID_DATA: "Invalid data, please try again!",
    REQUIRED_QUERY_PARAMETERS: "Please provide query parameters",
    NOT_ZONE_MEMBER_SO_UNABLE_TO_LEAVE: "Failure, Unauthorised you are not member of this zone, Only zone members authorized to leave the zone!",
    NOT_OWNER_OF_ANY_ZONE: "Failure, Unauthorised You are not owner of any zone.",
    NOT_OWNER_OF_THIS_ZONE_SO_UNABLE_TO_DELETE_ZONE_ATTENDEE: "Failure, Unauthorised You are not owner of this zone, Only zone owners authorized to delete zone attendee!",
    NOT_OWNER_OF_THIS_ZONE_SO_UNABLE_TO_BLOCK_ZONE_ORGANIZERS: "Failure, Unauthorised You are not owner of this zone, Only zone owners authorized to block the zone organizers!",
    NOT_OWNER_OF_THIS_ZONE_SO_UNABLE_TO_DELETE_ZONE_ORGANIZERS: "Failure, Unauthorised You are not owner of this zone, Only zone owners authorized to delete the zone organizers!",
    ONGOING_LIVE_EVENT_ASSOCIATED_WITH_ORGANIZE_SO_UNABLE_TO_REMOVE_ORGANIZER_FROM_ZONE_AT_THE_MOMENT: "You are not able to remove this organizer from the zone at the moment, because some live event is ongoing associated with this organize!",
    NOT_OWNER_OF_THIS_ZONE_ONLY_ZONE_OWNERS_AUTHORIZED_TO_SEND_INVITATION_TO_OWNER: "Failure, Unauthorised You are not owner of this zone, Only zone owners authorized to send invitations to owners!",
    ALREADY_REJECTED_ZONE_INVITATION: "Failure, You are already rejected invitation for the zone earlier!",
    ALREADY_REJECTED_ZONE_MEMBER_INVITATION_TRY_AGAIN_WHEN_GET_NEW_INVITATION: "Failure, You are already rejected invitation for the zone, please try again when you get a new invitation to be zone member!",
    ALREADY_REJECTED_ZONE_ORGANIZER_INVITATION_TRY_AGAIN_WHEN_GET_NEW_INVITATION: "Failure, You are already rejected invitation for the zone, please try again when you get a new invitation to be zone organizer!",
    ALREADY_REJECTED_ZONE_OWNER_INVITATION_TRY_AGAIN_WHEN_GET_NEW_INVITATION: "Failure, You are already rejected invitation for the zone, please try again when you get a new invitation to be zone owner!",
    ALREADY_ZONE_MEMBER_SO_CAN_NOT_REJECT_INVITATION: "Failure, You are already the member of the zone, you're not able to reject invitation now!",
    ALREADY_ZONE_MEMBER: "Failure, You are already the member of the zone!",
    INVALID_REQUEST_DATA: "Failure, invalid request data, try again later!",
    ALREADY_ZONE_ORGANIZER_SO_CAN_NOT_REJECT_INVITATION: "Failure, You are already the organizer in this zone, you're not able to reject invitation now!",
    ALREADY_ZONE_ORGANIZER: "Failure, You are already the organizer in this zone!",
    ALREADY_ZONE_OWNER_SO_CAN_NOT_REJECT_INVITATION: "Failure, You are already the owner of the zone, you're not able to reject invitation now!",
    ALREADY_ZONE_OWNER: "Failure, You are already the owner of the zone, please log in to access the zone.!",
    UNABLE_TO_SERVE_REQUEST_CONTACT_ADMINISTRATOR: "errorMessages.UNABLE_TO_SERVE_REQUEST_CONTACT_ADMINISTRATOR",
    NO_LONGER_ABLE_TO_DELETE_LAYOUT1: "You will no longer be able to delete the layout as",
    NO_LONGER_ABLE_TO_DELETE_LAYOUT2: "tickets are already sold out in",
    CITY_LAT_LONG_REQUIRED: "City name is without Latitude and longitude. Please select from suggestion",
    NO_FOLLOWERS_FOUND: "No followers found.",
    NO_FOLLOWINGS_FOUND: "No followings found.",
    DISCOUNT_CODE_EXIST: "Discount code already exist, try to add another code",
    DISCOUNT_CODE_INVALID: "Discount code is invalid",
    DISCOUNT_CODE_NOT_FOUND: "Discount code not found"
}

const emailAndPushNotiTitles = {
    PAYMENT_RECEIVED_FOR_AMOUNT_FOR_THE_EVENT: "Payment received for amount <paymentAmount> for the event, <eventName>, conducted on <eventConductedDate> at <eventVenue>",
    VISITER_LOGGED_THROUGH_EVENT_SHARED_BY_USER: "<visiterUserName> has logged in to PromoApp through the event <eventName> shared in <socialMediaPlatform> by user <refrenceUserName>",
    ATTENDEE_BOUGHT_INCLUDING_TICKETS_FESS: "<attendeeName> has bought <ticketQty> tickets for your event, <eventName>, including ticket fees",
    ATTENDEE_BOUGHT_EXCLUDING_TICKETS_FESS: "<attendeeName> has bought <ticketQty> tickets for your event, <eventName>, excluding ticket fees",
    PURCHASED_TICKETS_TO_EVENT: "You’ve just purchased <totalQty> tickets to <eventName>",
    TICKETS_REMAINING_FOR_YOUR_EVENT: "<remainingQty> tickets remaining for your event, <eventName>, in the ticket category, <ticketName>",
    PROFILE_HAS_BEEN_UPDATED: "Your profile has been updated at <profileUpdateTime> by <userName>",
    INTERESTED_EVENT_ABOUT_TO_CLOSE: "The event, <eventName>, you showed interest is about to close.",
    PAYMENT_FAILED_FOR_EVENT: "Failed!! Your payment for the event, <eventName> was not successful. Please try again.",
    USER_HAS_CHANGED_HIS_PLAN: "<userName> has changed his plan from <oldPlanId> to <newPlanId>",
    USER_WON_REWARD_ASSOCIATED_WITH_EVENT: "<userName> has won the reward <rewardTitle> associated with the event <eventName>",
    ALL_TICKETS_SOLD_OUT_FOR_EVENT: "All tickets sold out in ticket category, <ticketName>, for your event, <eventName>",
    USER_HAS_NOT_CLAIMED_REWARD_ASSOCIATED_WITH_EVENT: "<userName> has not claimed the reward <rewardTitle> associated with the event <eventName>",
    REWARD_CRITERIA_CHANGED_ASSOCIATED_WITH_EVENT: "The criteria for reward <rewardTitle> associated with event <eventName> has changed",
    CLICK_RECEIVED_FOR_EVENT_SHARED_IN: "Click received for the event <eventname> shared in <socialmediaplatform>. The click originated from <countryName> and device <deviceType> with the browser <browserName>",
    CLICK_RECEIVED_FOR_EVENT_SHARED_BY: "Click received for the event <eventName> shared by <refrenceUserName> in <socialMediaPlatform>. The click originated from <countryName> and device <deviceType> with the browser <browserName>",
    PAYOUT_FAILURE: "Payout failure of <eventName> event",
    USER_HAS_ELIGIBLE_REWARD_ASSOCIATED_WITH_EVENT: "<userName> is eligible for reward <rewardTitle> associated with the event <eventName>",
    USER_HAS_CLAIMED_REWARD_ASSOCIATED_WITH_EVENT: "<userName> has claimed the reward <rewardTitle> associated with the event <eventName>",
    REWARD_ASSOCIATED_WITH_EVENT_IS_ABOUT_TO_EXPIRE: `The following reward <rewardTitle> associated with event <eventName> is about to expire in <rewardExpiresInDays>`,
    ATTENDEE_SHARED_EVENT: "<attendeeName> has shared the event <eventname> in <socialType>",
    EVENT_HAS_BEEN_MODIFIED: "The following event, <eventName>, has been modified.",
    EVENT_HAS_BEEN_MODIFIED_AT_BY: "The following event, <eventName>, has been modified at <eventUpdateTime> by <userName>",
    USER_POSTED_COMMENT_ON_YOUR_EVENT: "<userName> has posted a comment on your event <eventName>",
    
    EVENT_CREATED: "Event created",
    EVENT_CREATED_NAME: "Event created: <eventName>",
    EVENT_SHARED: "Event Shared",
    EVENT_SHARED_NAME: "Event Shared: <eventName>",
    EVENT_VISITED: "Event visited",
    EVENT_VISITED_NAME: "Event visited: <eventName>",
    BECOME_ELIGIBLE_FOR_REWARD: "Become eligible for reward",
    BECOME_ELIGIBLE_FOR_REWARD_ON_EVENT: "Become eligible for reward on: <eventName> event",
    USER_BECOME_ELIGIBLE_FOR_REWARD: "User Become eligible for reward",
    REWARD_EXPIRED: "Reward expired",
    REWARD_CRITERIA_CHANGED: "Reward criteria changed",
    REMINDER_ON_UNCLAIMED_REWARD: "Reminder on unclaimed reward",
    ZONE_JOINING_REQUEST_REGISTERED: "Zone joining request registered",
    USER_LOGGED_IN_AFTER_CLICKING_AN_EVENT_IN_SOCIAL_PLATFROM: "User logged in after clicking an event in social platform",
    
    RESET_PASSWORD: "RESET PASSWORD",
    WELCOME_TO_PROMO_APP: "Welcome to promo app",
    EVANT_IS_LIVE: "You event is live!",
    YOU_ARE_NOW_ADMIN_FOR_EVENT: "You are now admin for a event!",
    VERIFY_EMAIL: "Verify email",
    YOU_ARE_NOT_INVITED_TO: "You are now invited to ",
    TICKET_PURCHASED: "Ticket purchased",
    TICKET_CANCELLED: "Ticket cancelled",
    LEAVE_ZONE_MEMBER: "Leave a zone member",
    REWARD_CLAIMED: "Reward claimed",
    TRANSACTION_FAILED_WHILE_BUYING_TICKET: "Transaction failed while buying ticket",
    INVITATION_ACCEPTED: "Invitation accepted",
    INVITATION_ACCEPTED_BY_ZONE_ORGANIZER: "Invitation accepted by zone organizer",
    INVITATION_REJECTED_BY_ZONE_ORGANIZER: "Invitation rejected by zone organizer",
    INVITATION_REJECTED: "Invitation rejected",
    ZONE_ORGANIZER_INVITATION_REJECTED: "Zone organizer invitation rejected",
    PLAN_CHANGED: "Plan changed",
    ACCOUNT_VERIFICATION_CODE: "Account verification code",
    COMMENT_POSTED_ON_EVENT: "Comment posted on event",
    BECOME_ZONE_MEMBER: "Become a zone member",
    INVITATION_BECOME_ZONE_MEMBER: "Invitation to become a zone member",
    LEAVE_ZONE_EVENT: "Leave a zone event",
    PAYOUT_PROCESSED: "Payout processed",
    EVENT_HAS_ENDED_PAYOUT_HAS_BEEN_PROCESSED: "event has ended. Payout has been processed",
    LEAVE_ZONE: "Leave a zone",
    REMOVED_FROM_ZONE: "Removed from the zone",
    ORGANIZER_REMOVED_FROM_ZONE: "Organizer removed from the zone",
    REJECT_ZONE_MEMBER: "Reject a zone member",
    REJECT_ZONE_OWNER: "Reject a zone owner",
    EVENT_CLAIMED: "Event claimed",
    USER_CLAIMED_EVENT_MIGHT_BE_INTEREST_TO_YOU: "has claimed an event which might be of interest to you",
    PROFILE_UPDATED: "Profile updated",
    EVENT_CANCELLED: "Event cancelled",
    REWARD_DISABLED: "Reward disabled",
    BECOME_ZONE_ORGANIZER: "Become a zone organizer",
    INVITATION_BECOME_ZONE_ORGANIZER: "Invitation to become a zone organizer",
    BECOME_ZONE_OWNER: "Become a zone owner",
    INVITATION_BECOME_ZONE_OWNER: "Invitation to become a zone owner",
    REWARD_ABOUT_TO_EXPIRED: "Reward about to expire",
    EVENT_ADMINISTATOR_REQUEST_REJECTED: "Event administrator request rejected",
    EVENT_ABOUT_TO_CLOSE: "Event about to close",
    EVENT_DETAILS_ARE_CHANGED: "Event details are changed",
    USER_SHOWN_INTEREST: "User shown interest",
    USER_PLANNING_TO_ATTEND: "User planning to attend",
    ANOTHER_USER_PLANNING_TO_ATTEND_EVENT: "Another user planning to attend event",
    EVENT_TICKET_ARE_SOLD_OUT_USER_PLANNING_TO_ATTEND_EVENT: "Event tickets are sold out, in which user planning to attend",
    USER_NOT_SHOWN_INTEREST: "User not shown interest",
    ANOTHER_USER_SHOW_INTEREST_IN_EVENT: "Another user show interest in event",
    EVENT_TICKET_ARE_SOLD_OUT_IN_WHICH_USER_INTERESTED: "Event tickets are sold out, in which user interested",
    REWARD_ASSOCIATED_WITH_EVENT: "Reward associated with event",
    REWARD_REMOVED: "Reward removed",
    WON_REWARD: "Won reward",
    USER_WON_REWARD: "User won Reward",
    BUYER_BOUGHT_TICKET: "Buyer bought ticket",
    BUYER_BOUGHT_TICKET_SELECTING_ABSORB_FEES_OPTION: "Buyer bought ticket - selecting the absorb fees option",
    BUYER_BOUGHT_TICKET_DESELECTING_ABSORB_FEES_OPTION: "Buyer bought ticket - deselecting the absorb fees option",
    STARTED_FOLLOWING: "Started following",
    ALL_TICKETS_SOLD_OUT: "All tickets sold out",
    TRANSACTION_FAILED: "Transaction failed",
    PAYMENT_RECEIVED: "Payment received",
    USER_STOPPED_FOLLOWING: "User stopped following",
    ALL_TICKETS_SOLD_OUT_FOR_EVENT: "All tickets sold out for your event: ",
    LIMITED_TICKETS_AVAILABLE: "Limited tickets available",
    LIMITED_TICKETS_AVAILABLE_FOR_YOUR_EVENT: "Only limited tickets available for your event, ",
    CANCELLED_EVENT: "Cancelled event: ",
    INVITATION_TO_BECOME_EVENT_ADMINISTRATOR: "Invitation to become an event administrator",
    BECOME_EVENT_ADMINISTRATOR: "Become an event administrator",
    WON_REWARD_ON_EVENT_SHARING_ON_SOCIAL_PLATFORM: "Won reward on event sharing on social platform",
    ATTENDEE_TRANSACTION_FAILED_FOR_YOUR_EVENT: "Attendee transaction failed for your event: ",
    EVENT_DETAILS_CHANGED: "Event detail changed: ",
    EVENT_CANCELLED_BY_ORGANIZER: "<eventName> has been cancelled by the organizer",
    USER_IS_PLANNING_TO_ATTEND_YOUR_EVENT: " is planning to attend your event, ",
    USER_HAS_SHOWN_INTEREST_IN_YOUR_EVENT: " has shown interest in your event, ",
    USER_HAS_NOT_SHOWN_INTEREST_IN_YOUR_EVENT: " has not shown interest in your event, ",
    TICKETS_ARE_NOT_AVAILABLE: ", but tickets are not available",
    YOU_HAVE_JUST_CANCELLED_YOUR_TICKETS_TO_EVENT: "You’ve just cancelled your tickets to ",
    ATTENDEE_CANCELLED_TICKET: "An attendee has just cancelled their tickets to ",
    EVENT_ORGANISER_CANCELLED_YOUR_TICKET: "Event organiser just cancelled your tickets to ",
    USER_HAS_STARTED_FOLLOWING_YOU: ", has started following you",
    USER_HAS_STOPPED_FOLLOWING_YOU: ", has stopped following you",
    USER_BECOME_ELIGIBLE_FOR_REWARD_ON_YOUR_EVENT: "User become eligible for reward on your: ",
    PAYOUT_HAS_BEEN_PROCESSED_FOR_EVENT: "Payout has been processed for ",
    IS_ASSOCIATED_WITH_EVENT: " is associated with the event ",
    ASSOCIATED_WITH_EVENT: " associated with the event ",
    FOLLOWING_REWARD: "The following reward ",
    REWARD_IS_DISABLED_WITH_EVENT: " is disabled for the event ",
    HAS_BEEN_MODIFIED_AT: ", has been modified at ",
    
    CANCEL_TICKET_BY_ATTENDEE_FOR_EVENT: "Cancel ticket by attendee for ",
    ABOUT_TO_EXPIRE: " is about to expire in ",
    REWARD_REMOVED_FROM_EVENT: " is removed from the event ",
    ELIGIBLE_FOR_REWARD: " is eligible for reward ",
    
    HAS_CLAIMED_REWARD: " has claimed the reward ",
    HAS_BOUGHT: " has bought ",
    TICKETS_FOR_YOUR_EVENT: " tickets for your event, ",
    FOR_YOUR_EVENT: ", for your event, ",

    "<attendeeName> has bought <totalQty> tickets for <eventName>": "<attendeeName> has bought <totalQty> tickets for <eventName>",
    "Ticket cancel for <mailDataObj.event_name> event": "Ticket cancel for <mailDataObj.event_name> event",
    "Event <eventName> created by <organiserName>": "Event <eventName> created by <organiserName>",
}

// Responce for frontend 
const privateMessage = {
    LOGIN_REQUIRED: "LOGIN_REQUIRED",
    PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
    NOT_INVITED: "NOT_INVITED",
    INVITE_INVALID_OR_EXPIRED: "INVITE_INVALID_OR_EXPIRED",
}

const eventPrivacyTypes = {
    PUBLIC: 1,
    PRIVATE: 2,
};

const dynamicLinks = {
    domainUriPrefix: "https://thepromoapp.page.link",
    androidPackageName: "com.thepromoapp.promo",
    androidFallbackLink: "https://play.google.com/store/apps/details?id=com.thepromoapp.promo",
    iosBundleId: "com.thepromoapp.promo",
    iosCustomScheme: "promoapp",
    iosFallbackLink: "https://apps.apple.com/in/app/the-promo-app/id1075964954",
    iosIpadFallbackLink: "https://apps.apple.com/in/app/the-promo-app/id1075964954",
    iosIpadBundleId: "com.thepromoapp.promo",

    email: "Donotreply@thepromoapp.com",
};

const eventAccessTypes = {
    LINK_ONLY: 1,
    INVITE_ONLY: 2,
    PASSWORD: 3,
};

const singupTypes = {
    SIGNUP_WITH_EMAIL: 1,
    SIGNUP_WITH_MOBILE: 2,
};

module.exports = {
    successMessages,
    errorMessages,
    emailAndPushNotiTitles,
    privateMessage,
    eventAccessTypes,
    eventPrivacyTypes,
    dynamicLinks,
    stringMessages,
    smsMessages,
    singupTypes
};